public enum Parameters {
    PatientID,
    Age,
    Gender,
    RBC,
    RBCDistributionWidth,
    Hemoglobin_HB,
    Hematocrit_HCT,
    WBC,
    NEU,
    Lymph,
    Mono,
    Eos,
    Baso,
    Plt,
    MPV,
    PlateletDistributionWidth,
    Sodium,     //electrolyes
    Potassium,  //electrolyes
    Chloride,   //electrolyes
    Bicarbonate,
    Serumcreatininelevel,
    GFR,
    BUN,
    Albumin_Creatin_Ratio,
    BNP,
    EF,
    FastingBloodSugar, //EF
    RandomBloodSugar,  //EF
    hemoglobin_A1c,     //EF
    RIDTs,  //RapidInfluenzaDiagnosticTests
    RMA, //Rapid Molecular Assay
    RT_PCR,
    RapidCellCultureTest, //+ve or -ve
    ViralTissueCellCulture,
    Immunofluorescence,
    PCR,
    NAATs,
    RapidEbolaAntigenTests,
    LaboratoryAntigenTests,
    EbolaAntibodyTesting,
    LP,
    Biopsy,
    XRay   ,
    CTScan,
    PET_CTScan,
    Bronchoscopy,
    WL,
    Breathlessness,
    Fatigue,
    SwollenAnklesAndLegs,
    ItchySkin,
    Fever,
    Tiredness,
    Cough,
    RunnyNose,
    Hunger,
    ExcessiveThirst,
    FrequentUrination,
    DryMouth,
    BlurredVision,
    SoreThroat,
    Headache,
    BodyAches,
    Insomnia,
    Nausea,
    Vomiting,
    MemoryProblems,
    Drowsiness,
    Diarrhea,
    BloodCoughing,
    BloodInUrine,
    Rash,
    Chills,
    StuffyNose,
    Conjunctivitis,
    RedEyes,
    Confusion,
    LossTasteSmell;
}
